#!/usr/bin/env bash

export _JAVA_AWT_WM_NONREPARENTING=1

redshift -l 43:-76 &

alacritty &
icecat &
flatpak run org.mozilla.firefox &


while true; do
  DATE=`date +"%F %R"`
  CPUTEMP=`sensors | grep "Core 0" | awk '{ print $3 }'`
  HDDTEMP=`sensors drivetemp-scsi-0-0 | grep temp1 | awk '{print $2}'`

  CPU0=`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq`
  FREQ0=`bc -l <<< "scale = 2; $CPU0 / 1000000"`

  CPU1=`cat /sys/devices/system/cpu/cpu1/cpufreq/scaling_cur_freq`
  FREQ1=`bc -l <<< "scale = 2; $CPU1 / 1000000"`

  CPU2=`cat /sys/devices/system/cpu/cpu2/cpufreq/scaling_cur_freq`
  FREQ2=`bc -l <<< "scale = 2; $CPU2 / 1000000"`

  CPU3=`cat /sys/devices/system/cpu/cpu3/cpufreq/scaling_cur_freq`
  FREQ3=`bc -l <<< "scale = 2; $CPU3 / 1000000"`

  xsetroot -name "Freq(GHz) $FREQ0 $FREQ1 $FREQ2 $FREQ3 | CPU $CPUTEMP | SDD $HDDTEMP | $DATE"
  sleep 5s
done &

DWM=`which dwm`
exec dbus-launch --sh-syntax --exit-with-session "$DWM" 2> "$HOME/.dwm.log"

